spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=m94pavan@gmail.com
spring.mail.password=jwin ewax sjjc zywl
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.default-encoding=UTF-8 


spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
# Database URL, username, and password
spring.datasource.url=jdbc:postgresql://localhost:5432/email_template_db
spring.datasource.username=postgres
spring.datasource.password=root

# JPA Configuration
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Exclude DataSource Auto Configuration

