spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=m94pavan@gmail.com
spring.mail.password=jwin ewax sjjc zywl
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.default-encoding=UTF-8
